### PR TITLE
Website in progress upload

### PR DESCRIPTION
**Pull request by dk4jo3**
## Description

Upload the new website files under the bigpanther.ca/doc folder

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have added tests where applicable.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dk4jo3** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dk4jo3** [comment]
recheck

**Comment by dk4jo3** [comment]
@harsimranmaan please let me know if I need to make any changes to merge this code. can't seem to make it work. thanks! :)

**Comment by harsimranmaan** [comment]
Thanks@dk4jo3 . I'll work on it this week

**Comment by harsimranmaan** [comment]
recheck

**Review by nicoletamaan — APPROVED** [review]

**Pull request merged**
